### PR TITLE
Fix "There was an error when creating the core" when start with custom SOLR_CORE

### PR DESCRIPTION
**Pull request by zindont**
When providing a **SOLR_CORE** and without **SOLR_CORE_CONF_DIR** (#31 related)
Start the container, it said **"There was an error when creating the core"** (screenshot below)

image

The issue occurred by **SOLR_CORE_CONF_DIR** was set to parent folder of config dir.
This variable use at https://github.com/RoSk0/bitnami-docker-solr/blob/9c5df5f5a231945edc951e51fd76f2611d2eef28/8/debian-10/rootfs/opt/bitnami/scripts/libsolr.sh#L190

**Changes**

Change the **SOLR_CORE_CONF_DIR** to the right path
It should be `${SOLR_SERVER_DIR}/solr/configsets/_default/conf` instead of `${SOLR_SERVER_DIR}/solr/configsets/_default`

**Benefits**

Fix the error **"There was an error when creating the core"** when start with custom **SOLR_CORE**

### CODE REVIEW

**Review by miguelaeh — APPROVED** [review]
Thank you very much!!!

LGTM!!!

**Comment by rosenbjerg** [comment]
We are still experiencing this issue
image

With the following values for SOLR_CORES and SOLR_CORE_CONF_DIR:
```yaml
solr:
  image: bitnami/solr:8
  environment:
    - SOLR_CORES=mycore
    - SOLR_CORE_CONF_DIR=/opt/config
  volumes:
    - ./solr-config:/opt/config
```

And this as the content of /opt/config:
image


I am not sure what causes this problem, but it comes from L199:
https://github.com/bitnami/bitnami-docker-solr/blob/4c791a3512f99aa8059825671e8eff2b6797e7b3/8/debian-10/rootfs/opt/bitnami/scripts/libsolr.sh#L194-L199

**Comment by miguelaeh** [comment]
Hi @rosenbjerg ,
Could you execute the command manually inside the container to see the results?

**Comment by rosenbjerg** [comment]
Hi @miguelaeh, I have tried running the command inside the container, after running the ENTRYPOINT + CMD
image

I'm not sure where to get a more detailed explanation on why Solr responded with 400 bad request

**Comment by miguelaeh** [comment]
mmm a 400 code (bad request) means the request was malformed, but it seems to be correct in your screenshot.

Re-checking your previous comment I just saw that you are mounting a local folder, does that folder has permissions for the `1001` user or `root` group?

**Comment by rosenbjerg** [comment]
Hi again @miguelaeh, 
I tried ensuring that the user with user-id 1001 had the required permissions for that with setfacl, but I still get the same error back.

I moved to testing locally, on my work laptop with Windows and WSL2. I can replicate here locally with this compose file:
```yaml
version: '3'
services:
  solr:
    image: bitnami/solr:8
    environment:
      - SOLR_CORES=globalindex
      - SOLR_CORE_CONF_DIR=/opt/config
    volumes:
      - ./solr-config:/opt/config
```
with the following folder structure:
image
image
image

The result is the same
image

And on WSL2, all mounted folders are exposed with 777 permissions, so permissions to the config folder shouldn't be the problem.

Could it be the configuration file that is somehow not compatible with the given version of Solr, or shouldn't that yield a different error?

Thank you for your time

**Comment by miguelaeh** [comment]
Hi @rosenbjerg ,

>And on WSL2, all mounted folders are exposed with 777 permissions, so permissions to the config folder shouldn't be the problem. 

I guess you mean the folder and all its content right? 

Have you tried a different solr config in case it is corrupted at some point? I mean, some config that you can ensure it should work and is tested in any other instance

**Comment by rosenbjerg** [comment]
Yes, I have just tried with the example `example-DIH` configuration from inside the image (the content of `example-DIH\solr\solr`), but it still fails

**Comment by miguelaeh** [comment]
Hi @rosenbjerg ,
I have just tested with the `example-DIH` and it works in my case, are you sure you are specifying the proper directory?
This is the docker-compose I used:
```
version: '3'
services:
  solr:
    image: bitnami/solr:8
    environment:
      - SOLR_CORES=globalindex
      - SOLR_CORE_CONF_DIR=/opt/bitnami/solr/example/example-DIH/solr/solr/conf
      - ```

**Comment by rosenbjerg** [comment]
Hi again @miguelaeh and thank you for the response. The problem was the structure of the directories we were mounting, as that was the parent folder of the conf folder instead of just the conf folder. 
Your example cleared that up, thanks

**Pull request merged**
